### ISSUE TITLE
POORLY WRITTEN README

### ISSUE THREAD

**Issue by ryanteo111** [OliverTeo288/infra#1]
poorly written readme!!!!!!!!!!

commands cannot be directly pasted

issue:
there shouldn't be $ in the commands written on the readme
for e.g. $ brew tap oliverteo288/infra
by copying the command into our terminal, it "assumes" the command starts with $ but it should start with the brew command

POORLY WRITTEN!!!!!!!!!!

**Comment by OliverTeo288** [comment]
meow
